spring:
  application:
    name: medicationReminder
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    validate-on-migrate: false
    enabled: true
    baseline-description: "init"
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

jwt:
  secret: ${JWT_SECRET}
  expiryTime: 86400000

server:
  port: 8080
