spring:
  application:
    name: medicationReminder
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    validate-on-migrate: false
    enabled: true
    baseline-description: "init"
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expiryTime: 86400000

ai:
  provider: openai
  openai:
    api-key: ${AI_OPENAI_API_KEY:default}
    model: gpt-5-mini

springdoc:
  swagger-ui:
    url: /v3/api-docs
server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

alert:
  from-email: ${ALERT_FROM_EMAIL}
  from-name: MediRemind
